---
- name: Define dotfiles paths
  vars:
    dotfiles:
      - { src: "~/.dotfiles/.config/nvim", dest: "~/.config/nvim" }
      - { src: "~/.dotfiles/.config/starship.toml", dest: "~/.config/starship.toml" }
      - { src: "~/.dotfiles/.config/wezterm", dest: "~/.config/wezterm" }
      - { src: "~/.dotfiles/.gitconfig", dest: "~/.gitconfig" }
      - { src: "~/.dotfiles/.tool-versions", dest: "~/.tool-versions" }
      - { src: "~/.dotfiles/.zsh", dest: "~/.zsh" }
      - { src: "~/.dotfiles/.zshrc", dest: "~/.zshrc" }

  block:
    - name: Remove existing files before linking
      file:
        path: "{{ item.dest }}"
        state: absent
      loop: "{{ dotfiles }}"

    - name: Link dotfiles
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ dotfiles }}"
