---
- name: link dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "~/.dotfiles/.config/nvim", dest: "~/.config/nvim" }
    - { src: "~/.dotfiles/.config/starship.toml", dest: "~/.config/starship.toml" }
    - { src: "~/.dotfiles/.config/wezterm", dest: "~/.config/wezterm" }
    - { src: "~/.dotfiles/.gitconfig", dest: "~/.gitconfig" }
    - { src: "~/.dotfiles/.zsh", dest: "~/.zsh" }
    - { src: "~/.dotfiles/.zshrc", dest: "~/.zshrc" }
