---
- name: Define dotfiles paths
  vars:
    dotfiles:
      - { src: "~/.dotfiles/.config/nvim", dest: "~/.config/nvim" }
      - { src: "~/.dotfiles/.config/starship.toml", dest: "~/.config/starship.toml" }
      - { src: "~/.dotfiles/.config/wezterm", dest: "~/.config/wezterm" }
      - { src: "~/.dotfiles/.gitconfig", dest: "~/.gitconfig" }
      - { src: "~/.dotfiles/.tool-versions", dest: "~/.tool-versions" }
      - { src: "~/.dotfiles/.zsh", dest: "~/.zsh" }
      - { src: "~/.dotfiles/.zshrc", dest: "~/.zshrc" }

  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: true
    state: link
  loop: "{{ dotfiles }}"
