---
- name: Include APT package list
  include_vars: vars/apt.yml
  tags:
    - apt
- name: Include DEB package list
  include_vars: vars/deb.yml
  tags:
    - apt

- block:
  - name: Register GPG key and repository for APT packages
    block:
      - name: Add GPG key for repository
        ansible.builtin.apt_key:
          url: "{{ item.value.gpg_key }}"
          keyring: "{{ item.value.keyring }}"
          state: present
        loop: "{{ apt | dict2items }}"
        when: item.value.gpg_key is defined and item.value.keyring is defined and item.value.repo is defined

      - name: Add APT repository
        ansible.builtin.apt_repository:
          repo: "{{ item.value.repo }}"
          filename: "{{ item.key }}"
          state: present
        loop: "{{ apt | dict2items }}"
        when: item.value.repo is defined
  - name: Update/Upgrade apt
    apt:
      update_cache: true
      upgrade: dist
    become: yes
  - name: Manage apt packages
    apt:
      name: "{{ item.key }}"
      state: "{{ item.value.state | default('present') }}"
    with_dict: "{{ apt }}"
  - name: Manage deb packages
    apt:
      deb: "{{ item.value }}"
      state: present
    with_dict: "{{ deb }}"
  become: yes
  when: ansible_os_family == "Debian"
  tags: apt

- name: Install zoxide
  become: yes
  block:
    - name: Install zoxide using apt
      apt:
        name: zoxide
        state: present
    - name: Setup zoxide
      lineinfile:
        path: "~/.zsh/tools.zsh"
        line: 'eval "$(zoxide init zsh)"'
        state: present
        create: yes

- name: Install bat
  become: yes
  block:
    - name: Install bat using apt
      apt:
        name: bat
        state: present
    - name: Setup bat
      file:
        src: /usr/bin/batcat
        dest: /usr/bin/bat
        state: link

- name: Install asdf
  vars:
    asdf_version: v0.14.0
  block:
    - name: Clone asdf repository
      git:
        repo: https://github.com/asdf-vm/asdf.git
        dest: "~/.asdf"
        version: "{{ asdf_version }}"
    - name: Add asdf to .zshrc
      lineinfile:
        path: "~/.zsh/tools.zsh"
        line: '. "$HOME/.asdf/asdf.sh"'
        state: present
        create: yes

- name: Install starship
  block:
    - name: Download starship installation script
      get_url:
        url: https://starship.rs/install.sh
        dest: /tmp/starship_install.sh
        mode: '0755'

    - name: Run starship installation script
      command: /tmp/starship_install.sh -f
      args:
        creates: /usr/local/bin/starship

    - name: Add starship to .zshrc
      lineinfile:
        path: "~/.zsh/tools.zsh"
        line: 'eval "$(starship init zsh)"'
        state: present
        create: yes
