---
- name: Include APT package list
  include_vars: vars/apt.yml
  tags:
    - apt

- name: Install apt packages
  block:
    - name: Update/Upgrade apt
      apt:
        update_cache: true
        upgrade: dist
      become: true
    - name: Manage apt packages
      apt:
        name: "{{ item.key }}"
        state: "{{ item.value.state | default('present') }}"
      with_dict: "{{ apt }}"
  tags: apt
  when: ansible_os_family == "Debian"
  become: true

- name: Install jless
  become: true
  block:
    - name: Download jless zip file
      get_url:
        url: https://github.com/PaulJuliusMartinez/jless/releases/download/v0.9.0/jless-v0.9.0-x86_64-unknown-linux-gnu.zip
        dest: /tmp/jless.zip
    - name: Unzip the downloaded zip file
      unarchive:
        src: /tmp/jless.zip
        dest: /tmp/
    - name: Copy the jless file to /usr/bin
      copy:
        src: /tmp/jless
        dest: /usr/bin/jless
        mode: '0755'
  when: ansible_os_family == "Debian"


- name: Install difftastic
  become: true
  block:
    - name: Download difftastic tar file
      get_url:
        url: https://github.com/Wilfred/difftastic/releases/download/0.60.0/difft-x86_64-unknown-linux-gnu.tar.gz
        dest: /tmp/difftastic.tar.gz
    - name: Unarchive the downloaded tar file
      unarchive:
        src: /tmp/difftastic.tar.gz
        dest: /tmp/
    - name: Copy the difftastic file to /usr/bin
      copy:
        src: /tmp/difft
        dest: /usr/bin/difft
        mode: '0755'
  when: ansible_os_family == "Debian"

- name: Install zoxide
  become: true
  block:
    - name: Install zoxide using apt
      apt:
        name: zoxide
        state: present
    - name: Setup zoxide
      lineinfile:
        path: "~/.zsh/tools.zsh"
        line: 'eval "$(zoxide init zsh)"'
        state: present
        create: yes
  when: ansible_os_family == "Debian"

- name: Install bat
  become: true
  block:
    - name: Install bat using apt
      apt:
        name: bat
        state: present
    - name: Setup bat
      file:
        src: /usr/bin/batcat
        dest: /usr/bin/bat
        state: link
  when: ansible_os_family == "Debian"

- name: Install asdf
  vars:
    asdf_version: v0.14.0
  block:
    - name: Clone asdf repository
      git:
        repo: https://github.com/asdf-vm/asdf.git
        dest: "~/.asdf"
        version: "{{ asdf_version }}"
    - name: Add asdf to .zshrc
      lineinfile:
        path: "~/.zsh/tools.zsh"
        line: '. "$HOME/.asdf/asdf.sh"'
        state: present
        create: yes

- name: Install starship
  block:
    - name: Download starship installation script
      get_url:
        url: https://starship.rs/install.sh
        dest: /tmp/starship_install.sh
        mode: '0755'

    - name: Run starship installation script
      command: /tmp/starship_install.sh -f
      args:
        creates: /usr/local/bin/starship

    - name: Add starship to .zshrc
      lineinfile:
        path: "~/.zsh/tools.zsh"
        line: 'eval "$(starship init zsh)"'
        state: present
        create: yes

- name: Install ffuf
  become: true
  block:
    - name: Download ffuf binary
      get_url:
        url: https://github.com/ffuf/ffuf/releases/download/v2.1.0/ffuf_2.1.0_linux_amd64.tar.gz
        dest: /tmp/ffuf_amd64.tar.gz
        mode: '0755'
    - name: Unarchive the downloaded tar file
      unarchive:
        src: /tmp/ffuf_amd64.tar.gz
        dest: /tmp/
    - name: Copy the ffuf file to /usr/bin
      copy:
        src: /tmp/ffuf
        dest: /usr/bin/ffuf
        mode: '0755'
  when: ansible_os_family == "Debian"
