---
- name: Change default shell
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /bin/zsh
  become: yes

- name: Install CodeNewRoman font
  vars:
    font_url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/CodeNewRoman.zip"
    font_zip: "/tmp/CodeNewRoman.zip"
    font_dir: "/usr/local/share/fonts"
  become: yes
  block:
    - name: Ensure the font directory exists
      file:
        path: "{{ font_dir }}"
        state: directory
        mode: '0755'

    - name: Download the font zip file
      get_url:
        url: "{{ font_url }}"
        dest: "{{ font_zip }}"

    - name: Unzip the font file
      unarchive:
        src: "{{ font_zip }}"
        dest: "{{ font_dir }}"
        remote_src: yes

    - name: Update font cache
      command: fc-cache -f -v

    - name: Clean up the downloaded zip file
      file:
        path: "{{ font_zip }}"
        state: absent
