scan_timeout = 50

[aws]
disabled = true

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[c]
format = "via [$symbol]($style)"

[directory]
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "…/"

[docker_context]
format = "via [$symbol]($style)"

[git_branch]
symbol = " "
