scan_timeout = 10

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold green)"

[directory]
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "…/"

[aws]
disabled = true

[c]
format = "via [$symbol]($style)"

[docker_context]
format = "via [$symbol]($style)"

[git_branch]
symbol = " "

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
show_always = true
