---
- name: Playbook to manage my dotfiles
  hosts: localhost
  connection: local
  tasks:
    # git module is not used for simplicity
    - name: Install dotfiles repository via ssh or https
      tags: always
      args:
        creates: "{{ ansible_env.HOME }}/.dotfiles"
      shell: |
        if ssh -T git@github.com 2>&1 | grep -q "successfully"; then
          git clone git@github.com:tkuramot/dotfiles.git "{{ ansible_env.HOME }}/.dotfiles"
        else
          git clone https://github.com/tkuramot/dotfiles.git "{{ ansible_env.HOME }}/.dotfiles"
        fi

    - import_tasks: tasks/link_files.yml
      tags: links

    - import_tasks: tasks/install_packages.yml
      tags: packages

    - import_tasks: tasks/install_manual.yml
      tags: manual
