---
- name: Playbook to manage my dotfiles
  hosts: localhost
  connection: local
  tasks:
    - name: Load custom vars
      include_vars: ../vars.yml
      tags:
        - always

    # Install dotfiles repository via ssh when possible otherwise via https
    - name: Test ssh connection to GitHub
      command: ssh -T git@github.com
      register: ssh_test
      ignore_errors: true
      changed_when: false
      failed_when: ssh_test.rc not in [1, 255]
      tags:
        - always
    - name: Make sure dotfiles are present
      git:
        repo: "{{ 'git@github.com:tkuramot/dotfiles.git' if ssh_test.rc == 1 else 'https://github.com/tkuramot/dotfiles.git' }}"
        dest: ~/.dotfiles
        accept_hostkey: true
      tags:
        - always

    - import_tasks: tasks/link_files.yml
      tags:
        - links

    - import_tasks: tasks/packages.yml
      tags:
        - packages
