---
- name: Playbook to manage my dotfiles
  hosts: localhost
  connection: local
  tasks:
    - name: load custom vars
      include_vars: ../vars.yml
      tags:
        - always

    - name: Make sure dotfiles are present
      git:
        repo: https://github.com/tkuramot/dotfiles.git
        dest: ~/.dotfiles

    - include_tasks: tasks/link_files.yml
      tags:
        - links

    - include_tasks: tasks/packages.yml
      tags:
        - packages
